version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - 5173:5173
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=mongodb+srv://sv:PJOzYnTTcjhQHiMR@cluster0.v1flhbm.mongodb.net/?retryWrites=true&w=majority

